### ISSUE TITLE
Please merge 'unstable' to master and do release

### ISSUE THREAD

**Issue by lechat** [salimfadhley/jenkinsapi#331]
Hi, @salimfadhley

Unstable branch is pretty stable now and I think that it is time to merge it to master and do new release. Also, it would be nice to update ReadTheDocs site together with the new release.

**Comment by salimfadhley** [comment]
Will do!

**Comment by salimfadhley** [comment]
This was done. Could you spare a moment to review pull requests? I closed a
few yesterday.

**Comment by rocktavious** [comment]
When will the next release be? and what will its version be?  I'm looking to start using the project again and pypi has the last release tagged on 2015-1-13 ... has there really been no changes since then?

**Comment by salimfadhley** [comment]
We can make a release - any objections?

**Comment by lechat** [comment]
No objections from me.

**Comment by salimfadhley** [comment]
A release has been made. 

new docs are here: http://jenkinsapi.readthedocs.org/en/latest/
