### ISSUE TITLE
KeyError: 'url' in 0.2.26

### ISSUE THREAD

**Issue by GuyShaanan** [salimfadhley/jenkinsapi#336]
This code works in 0.2.25:
j = Jenkins(baseurl, username, password)
if j:
    do_things()

When using 0.2.26, I get exception in jenkinsbase.py:102 when evaluating the 'if j':
data = self.get_data(self.python_api_url(folder['url']))

File "build/bdist.linux-x86_64/egg/jenkinsapi/jenkinsbase.py", line 102, in process_job_folder
KeyError: 'url'

Jenkins version: 1.584.
Thanks.

**Comment by lechat** [comment]
Hi,

I think that this is caused by Cloudbees Folders plugin. Perhaps something changed in their API.

**Comment by lechat** [comment]
Hi,

I found the problem in code. While I am fixing it, you can change your code to this:

```
j = Jenkins(baseurl, username, password)
if j is not None:
    do_things()
```

**Comment by lechat** [comment]
Fixed it.
