### ISSUE TITLE
NoBuildData error when builds are present

### ISSUE THREAD

**Issue by mwasilew** [salimfadhley/jenkinsapi#339]
I was using v0.2.18 for a long time. Recently I installed my scripts on a new machine and installed jenkinsapi using pip. The version of the jenkinsapi was 0.2.26 and my scripts started failing. I did a minimized test case (below) and bisected the code. The first bad commit appears to be: 7efadca61a5a57e0a33b97a2b6d51007c9cc2d2f

Could you possibly help solving the issue? Might it be caused by old Jenkins version?

Test case below:
```
from jenkinsapi.jenkins import Jenkins

JENKINS_URL = 'https://ci.linaro.org/jenkins/'
J = Jenkins(JENKINS_URL)
project = 'linux-linaro-stable-lsk-v3.14'
job = J[project]
print job.get_build_dict()
```

trace:
```
Traceback (most recent call last):
  File "minimal_test.py", line 7, in <module>
    print job.get_build_dict()
  File ".venv/jenkinsapi/jenkinsapi/job.py", line 275, in get_build_dict
    raise NoBuildData(repr(self))
jenkinsapi.custom_exceptions.NoBuildData: <jenkinsapi.job.Job linux-linaro-stable-lsk-v3.14>
```

**Comment by lechat** [comment]
Yes, this could be caused by old Jenkins version. Could you do a quck check? Navigate to a job and then click on API link in bottom right. On API page there should be a text about minimizing amount of data by using tree api. Do you have this text? If you do, what happens when you click on any of the examples?

**Comment by mwasilew** [comment]
Text is there. The examples work pretty well:
https://ci.linaro.org/api/
I did some debugging and I noticed that URLs are changed from 
https://ci.linaro.org/api/json?tree=jobs%5Bname%5D
to 
https://ci.linaro.org/api/json?tree=jobs%255Bname%255D
as if the '%' itself was encoded. It doesn't happen with my local jenkins instance so there must be something in the middle that changes the URLs - proxy? Any hints are appreciated.

**Comment by mwasilew** [comment]
It looks it was jenkins-behing-apache configuration bug. Please close this issue. The root cause wasn't in the jenkinsapi code. The fix was like this:

```
-  RewriteRule ^/jenkins/(.*) https://%{HTTP_HOST}/$1 [R,L]
+  RewriteRule ^/jenkins/(.*) https://%{HTTP_HOST}/$1 [redirect,noescape,last]
```

**Comment by lechat** [comment]
Thanks for investigating!
