### ISSUE TITLE
Can't call job.invoke with jenkins 1.602

### ISSUE THREAD

**Issue by jonathansp** [salimfadhley/jenkinsapi#340]
invoke() method raises an exception when called from Job class. Jenkins API URL returns 404.

ERROR:root:Failed request at http://localhost:8080/queue/item/12/api/python with params: None 
HTTPError: HTTPErro... Found',)

It worked fine in version 1.5.

**Comment by lechat** [comment]
I think that this is a bug in Jenkins. Quck search in Jenkins bugtracker finds this: https://issues.jenkins-ci.org/browse/JENKINS-27256

If API endpoint is not working - there is nothing can be done from ``jenkinsapi`` side.

**Comment by lechat** [comment]
The issue have been fixed in Jenkins 1.605

**Comment by jonathansp** [comment]
Thanks a lot.
