### ISSUE TITLE
Build.py does not contain get_builtOn(self)

### ISSUE THREAD

**Issue by peterhaans** [salimfadhley/jenkinsapi#344]
The _data contains the builtOn parameter. The api does not contain a get_builtOn function.
Please add in build.py:

    def get_builtOn(self):
        """
        Return a string of builtOn.
        """
        return self._data["builtOn"]

**Comment by salimfadhley** [comment]
Feel free to add this (with a test) as a pull request.

Can you explain what the use-case for this is? I'm not familiar with this field - is it returning the time of the build or the name of the executor that did the building?

**Comment by lechat** [comment]
This feature was added in PR #383
