### ISSUE TITLE
Workflow (offcial) plugin job doesn't keep parameters under actions

### ISSUE THREAD

**Issue by zzzuzik** [salimfadhley/jenkinsapi#346]
In case if somebody run into it, the new CloudBee's WorkFlow plugin
https://wiki.jenkins-ci.org/display/JENKINS/Workflow+Plugin
It's job doesn't have `parameterDefinitions` under `"actions"`, but rather under `"property"`
The rest of my regular jobs also have their property definitions under `property` 
To handle has_params exception I have to do this in job.py
``` python
return any("parameterDefinitions" in a for a in (self._data["actions"] or self._data["property"]) if a)
```

**Comment by lechat** [comment]
Please submit this as a pull request.

**Comment by zzzuzik** [comment]
Here are we go #347

**Comment by zzzuzik** [comment]
There is another usage of `parameterDefinitions` in `get_params`
If you like, you can use this PR #348 to look into `property` as well

**Comment by lechat** [comment]
Merged. Thanks!
