### ISSUE TITLE
Mark build as unstable

### ISSUE THREAD

**Issue by jhasse** [salimfadhley/jenkinsapi#352]
Would be great to add the possibility to mark a build as unstable using Python. Currently I have to use the Groovy Postbuild Plugin. Also see http://stackoverflow.com/questions/8148122/how-to-mark-a-build-unstable-in-jenkins-when-running-shell-scripts

Is that possible?

**Comment by lechat** [comment]
Perhaps groovy script has access to Jenkins java api, which has access to a method that sets build status. AFAIK, there is nothing in Jenkins UI where you can do the same, so this library is not able to do the same.
