### ISSUE TITLE
I want to restructure the project so that the root folder contains all the build-scripts and IDE config

### ISSUE THREAD

**Issue by salimfadhley** [salimfadhley/jenkinsapi#353]
I'd like everything that's currently in the root directory of the project to be in src/

The contents of misc/ will be moved to the root directory of the project. This will contain build & setup scripts. It will also contain config files that will make use with common IDEs (e.g. IntelliJ, Sublime) easier - the project will be automatically importable and "just work" in those environments.

I propose to make this change in the unstable branch and then merge subject to review from anybody activly involved with the project.

Sal

**Comment by lechat** [comment]
It doesn't affect me at all as I am not using any of IDEs, I work in vim.

**Comment by salimfadhley** [comment]
I also plan to add some bootstrapping scripts so that anybody with basic
skill can build dev environments.

**Comment by lechat** [comment]
I am a bit puzzled. It works fine after ``pip install jenkinsapi``, what is missing?

**Comment by lechat** [comment]
Also, I think that adding ``src`` folder is not exactly necessary for a library that have nothing else but sources.
