### ISSUE TITLE
Ability to trigger a build from a Job

### ISSUE THREAD

**Issue by meteorfox** [salimfadhley/jenkinsapi#354]
I've looked at the examples, docs, unit tests, and even searched the github issues, but I can't seem to find how does one submit a parametrized build, or even just a normal build, of a Job using this library.

Ideally, I'm looking for a function that takes the Job object, or a job name, and does the POST to submit the build, which then returns a Build object, or the build number.

Thanks ahead.

**Comment by lechat** [comment]
Hi,

Here is the code:

```
# Assume that Jenkins object in jenkins variable
my_job = jenkins['my_job']
# Trigger the job with parameters
q = my_job.invoke(build_params={'param1': 'some_value', 'param2': 'some_other_value'})
# invoke returns QueueItem, we need to ask it for a build object
build_num = q.get_build_number()
# Now we ask job to give us build by number
build = my_job.get_build(build_num)
```

You could see more help in jenkinsapi_tests/systests/test_invocation.py

Hope this helps.

**Comment by meteorfox** [comment]
Thanks! Probably it'd be helpful to include this same example in the docs. :)
