### ISSUE TITLE
Calling len() on a jenkinsapi.Jobs object fails with TypeError: object of type 'instancemethod' has no len()

### ISSUE THREAD

**Issue by columbusmonkey** [salimfadhley/jenkinsapi#357]
From jenkinsapi/jobs.py:25:

    def __len__(self):
        return len(self.keys)

Should that be `self.keys()` ?

**Comment by zzhu06** [comment]
I have the same question!

**Comment by lechat** [comment]
Obvious bug not covered by unit test. Shall be fixed.

**Comment by lechat** [comment]
Fixed
