### ISSUE TITLE
[feature idea] jenkins remote control CLI

### ISSUE THREAD

**Issue by mattvonrocketstein** [salimfadhley/jenkinsapi#366]
I want a jenkins remote control CLI.  More or less what I need is a clone of [the netflix cli](https://github.com/Netflix-Skunkworks/jenkins-cli) which has better support for multiple jenkins instances (the original is also in perl.. a python rewrite is a bonus).  Other than that, I think the motivation for a CLI tool is obvious since it's the same as the motivation for jenkinsapi as a library: curling instructions into jenkins is tedious and breaks down for complicated stuff.  

I think I can put this together pretty quickly, and although it seems like it could easily be a third-party app it would be nice to leverage the existing testing harness that jenkinapi uses without a lot of copy/pasting.  

What do you guys think, is something like this attractive to put into core?

**Comment by salimfadhley** [comment]
Neat idea - it should be a different package that could depend on our
package.
