### ISSUE TITLE
Create jenkins view from API 

### ISSUE THREAD

**Issue by rayeesnp** [salimfadhley/jenkinsapi#371]
Is there any way i can create view with jenkins API ?

**Comment by lechat** [comment]
Sure there is:

https://github.com/salimfadhley/jenkinsapi/blob/master/examples/how_to/create_views.py

**Comment by rayeesnp** [comment]
Great, Thanks 

Is there any way i can create job under specific view or add job to a view ?

by default jobs get created under all view

**Comment by lechat** [comment]
``View`` object has ``add_job`` method and also acts as a dict like container for jobs in the view.

**Comment by rayeesnp** [comment]
Thanks a  found that
