### ISSUE TITLE
Fetches an excessive amount of job info

### ISSUE THREAD

**Issue by pauldraper** [salimfadhley/jenkinsapi#377]
```python
Jenkins('https://jenkins.example.com/')
```

hangs.

```python
Jenkins('https://jenkins.example.com/', lazy=True)
```

does not hang.

```python
Jenkins('https://jenkins.example.com/', lazy=True).get_build_info('example')
```

hangs.

---

It seems that the client is trying to fetch info for *all* jobs. I work with 60 people doing branch-based development, which translates to ~50 projects (jobs) on each of ~60 branches (folders) at any given time, this my interest in jenkinsapi, as an automated way to query and mange Jenkins.

But I unfortunately it isn't usable, since it requests thousands of jobs, when I just need info for a single job.

**Comment by lechat** [comment]
I have similar Jenkins setup and I am not experiencing such issue.

Are you sure that you are using latest version? I can't find ``get_build_info()`` function in Jenkins object, perhaps it was there but have been removed.

The current version uses Jenkins tree api, and doesn't try to fetch whole info, but only what is necessary for particular place. Having your number of Jenkins jobs, I would think that the bottleneck would be in Jenkins itself, or in network latency. 

Have you tried to run the same script on Jenkins box? Does that make any difference? Could you try running this query in Jenkins directly to find how long it takes Jenkins to produce result:

<jenkins_url>/api/json/tree=jobs[name,url,color]

**Comment by jmreicha** [comment]
@pauldraper Seeing the slow behavior as well.  Did you ever find a solution and/or workaround?
