### ISSUE TITLE
Get build number and Status

### ISSUE THREAD

**Issue by rayeesnp** [salimfadhley/jenkinsapi#380]
Hi,

I am using jenkins API to trigger build, I may trigger multiple build and job will be in Queue

After start job, i want to check each jobs build number and status  from jenkin object?  currently build job API not returing anything to get this info, any idea how to resolve this ?

  def build_job(self, jobname, params=None):
        """
        Invoke a build by job name
        :param jobname: name of exist job, str
        :param params: the job params, dict
        :return: none
        """
        self[jobname].invoke(build_params=params or {})

**Comment by lechat** [comment]
You can get all patterns either from examples or from tests.

Here is what you need to do:
```
        job_name = 'foo'
        job = self.jenkins[job_name]
        q_item = job.invoke()
        q_item.block_until_building()
        # Simple build number
        number = qq.get_build_number()
        # Build object
        build = qq.get_build()
```
