### ISSUE TITLE
About new job creation

### ISSUE THREAD

**Issue by sachinshelke28** [salimfadhley/jenkinsapi#384]
Hello,

I am trying to create new job using rest API with node.js.
Is there any docs available for it?

**Comment by lechat** [comment]
AFAIK, no docs. Take a look at our source to get idea how it is done.

**Comment by sachinshelke28** [comment]
I also tried out according to docs but I am not able to do that. Please tell me specific solution to for create new job. How can I do?

**Comment by lechat** [comment]
Look here:

https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi/jobs.py#L97

You need to POST to http://jenkins/createItem and pass job's config.xml as data and {'name': job_name} as parameters.
