### ISSUE TITLE
Installation failed due to pytz

### ISSUE THREAD

**Issue by nannanitinkumar** [salimfadhley/jenkinsapi#386]
Processing dependencies for jenkinsapi==0.2.28
Searching for pytz>=2014.4
Reading https://pypi.python.org/simple/pytz/
Download error on https://pypi.python.org/simple/pytz/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
Couldn't find index page for 'pytz' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo failed -- Some packages may not be found!
No local packages or download links found for pytz>=2014.4
error: Could not find suitable distribution for Requirement.parse('pytz>=2014.4')

Not able to install please let me know how to proceed.

**Comment by salimfadhley** [comment]
How were you installing this?

What version of Python are you running?

Which OS?

**Comment by nannanitinkumar** [comment]
Hi,

OS is windows 7
Python version is python272

Run command is
Python setup.py installs

Thank you in advance
Nitin Kumar

**Comment by lechat** [comment]
This has nothing to do with pytz or jenkinsapi - the error says that the site pypi.python.org cannot be resolved to ip. Please check your network settings.

**Comment by salimfadhley** [comment]
Yeah, this bit "Download error on https://pypi.python.org/simple/pytz/: [Errno 11004] getaddrinfo failed -- Some packages " literally means that your pip couldn't resolve pypi.python.org - probably cause is an incorrect proxy setting. Are you behind a corporate firewall? If so you might want to set HTTP_PROXY.

**Comment by nannanitinkumar** [comment]
Can't we in install everything offline??
I don't think it's possible for me to change the HTML proxy

Please let me know is there any alternative

Thank you
Nitin Kumar

**Comment by salimfadhley** [comment]
Yes, you can install everything offline. If you manually install all the dependencies then Pip will have no additional requirments to fetch.

Setting an HTTP (not HTML) proxy only requires you to set an environment variable. You can do that in whatever script you use to build your project. Research HTTP_PROXY.
