### ISSUE TITLE
Use jenkinsapi with py2exe

### ISSUE THREAD

**Issue by B3J4y** [salimfadhley/jenkinsapi#402]
I tried to create an exe with py2exe. The source python script uses jenkinsapi. It give me an runtime exception which claims an error in jenkinsapi\__init__.pyc, line 69. I thought to fix the problem I have to include pkg_resources but it doesn't solve the problem.

I attach the log and the py2exe file. Both is in the same file.
[log.txt](https://github.com/salimfadhley/jenkinsapi/files/31752/log.txt)

**Comment by salimfadhley** [comment]
Can you try this with the latest version from GitHub?

**Comment by B3J4y** [comment]
This is working.

Thank you.
