### ISSUE TITLE
Jenkins API REST methods

### ISSUE THREAD

**Issue by Amali89** [salimfadhley/jenkinsapi#404]
Hi All,

I am new to Jenkins. Can anyone please provide link to check available REST methods in Jenkins.
I checked below link, But it doesn't contain the available methods as REST.
https://jenkinsapi.readthedocs.org/en/latest/

Appreciate support.

Thank you,
Amali

**Comment by lechat** [comment]
Hi,

Jenkinsapi library does not provide any REST services, it is a library that uses Jenkins REST API. 

You need to check Jenkins documentation.

**Comment by Amali89** [comment]
Hi,

I am looking for REST methods available in Jenkins. Couldn't find any resources.
Does anyone know any link?

Thank you.

**Comment by lechat** [comment]
Please ask this question in Jenkins mailing lists.
