### ISSUE TITLE
jobs are scheduled twice

### ISSUE THREAD

**Issue by pgrandin** [salimfadhley/jenkinsapi#413]
Hi,

I'm trying to trigger jobs using jenkinsapi. I am able to do it, but each job is actually scheduled twice : the first time it's scheduled with the parameters as I would expect, and the second time is it scheduled as a downstream project of itself : "Started by upstream project <same project>"

When I schedule the jobs using curl and the command line, the jobs are scheduled only once as I would expect. 

The code is pretty straightforward :
```
    if (server.has_job(job_name)):
        job_instance = server.get_job(job_name)
        print job_instance.python_api_url(job_name)
        server.build_job(job_name, params)
```
Anybody ever faced this issue?

**Comment by JinmingZhao** [comment]
Hi, Pierre


Ｉ don' t know  if you have the default parameters , if there is default parameters in the configuretion ,and the parameters  you given later, maybe be happend as you have met. I  just guess this issue, and you could create two jobs to verify this issue.

Best Regards,
Jinming


------------------ Original ------------------

**Comment by lechat** [comment]
Hi,

I haven't seen such issue before. Could you try raising logging level in your script and paste here the output?

Thanks!

**Comment by pgrandin** [comment]
It looks like this was caused by a misconfigured plugin on our side.
Thanks and sorry for the noise!
(what's really weird is that it was only happening when using the python api, not curl!)
