### ISSUE TITLE
get/post and http/https

### ISSUE THREAD

**Issue by hacklint** [salimfadhley/jenkinsapi#426]
Hi,
Not sure if this is a problem in jenkinsapi or lower layers, but adding it here hoping it may help someone.

I run a jenkins instance on localhost, which SHOULD be accessed using https
Somehow that elusive 's' was dropped and I used http instead.

Then getting a job instance usingjenkinapi and trying to call disable() on it failed with a 405 which
surprised me since support for using both GET and PUT seems to be present in jenkinsapi
since way back.

Looking at the httpd output:
httpd_1         | 172.18.0.1 - - [04/Mar/2016:08:30:47 +0000] "POST /jenkins/job/Secundus/disable HTTP/1.1" 301 185 "-" "python-requests/2.9.1" "-"
httpd_1         | 172.18.0.1 - - [04/Mar/2016:08:30:47 +0000] "GET /jenkins/job/Secundus/disable HTTP/1.1" 405 202 "-" "python-requests/2.9.1" "-"
...it looks like a POST is given a 301 - (Moved permanently) and retries at the new address (presumably) - but using a GET request. From my brief look in the source i think this should be handled with an exception and a new request using PUT - so my hypothesis is that the second
GET is made by someone else (request?) than jenkinsapi.

Anyway, using the right protocol (https) worked as planned, but the behaviour shown when using http was quite confusing and could probably be handled a bit better.

jenkinsapi 0.2.29
python-requests 2.9.1

Regards, /A

**Comment by lechat** [comment]
Hi,

Jenkinsapi tries to stay updated every time it asks something from Jenkins. When it asks Jenkins to disable job (PUT), it immediately requests job details, this is normal and not exceptional.

For losing http - it is possible that your Jenkins doesn't know itself, that it is supposed to be run on https. There is a setting that sets Jenkins url and by default it is set to http (Manage Jenkins->Configure System->Jenkins URL). Could you check that out?

**Comment by salimfadhley** [comment]
Yep, that's seconded: JenkinsAPI only ever follows the URLs provided by the server. You can check for yourself by looking at the structure returned by the Jenkins REST API. I expect you will find that all the URLs are http and not https.
