### ISSUE TITLE
How to download an artifact from a build

### ISSUE THREAD

**Issue by grayaii** [salimfadhley/jenkinsapi#428]
I can't figure out how to download an artifact from a build.

Looking at http://jenkinsapi.readthedocs.org/en/latest/api.html?highlight=artifact I see a function called grab_artifacts, but I don't know what what the artifact "id" is or how to get it.

I think this is exactly what I need:
http://jenkinsapi.readthedocs.org/en/latest/artifact.html
But looking at the function signature: jenkinsapi.artifact.Artifact(filename, url, build) I don't see a way to pass credentials.  I'm hoping that the "build" parameter will have the creds.

Here is what I tried so far:
```python
from jenkinsapi.jenkins import Jenkins
from jenkinsapi.artifact import Artifact

host = 'http://myjenkins.it:8080/'
J = Jenkins(host, username='alex.gray', password='mypassowrd')

job = J['_foo']

r = job.invoke(block=True, build_params={'FOO':'{0}'.format('my param value')})
b = r.get_build()
print('status       : {}'.format(b.get_status()))
print('build #      : {}'.format(b.get_number()))
# This shows that this build has foo.txt as an artifact. Yay:
print('artifact_dict: {}'.format(b.get_artifact_dict())) 
print('is_building  : {}'.format(b.is_running()))

# I now have my build object, b
# so I should be able to download an artifact from this particular build:
a = b.get_artifacts()
print(a) 
print('----')
# OK, get_artifacts is NOT the function that we want. Lets try the Artifact class:
a = Artifact('foo.txt', host, b)
print(a)
print(dir(a))
print(a.save_to_dir('.'))
```
When i a.save_to_dir, I get this error:

ERROR:root:Failed request at http://myjenkins.it:8080/fingerprint/7c90c00198694d3328bf10d66591d704/api/python with params: None
./foo.txt

Any idea how I can download an artifact from the build object?

Thanks

**Comment by lechat** [comment]
Please take a look at the system test:

https://github.com/salimfadhley/jenkinsapi/blob/master/jenkinsapi_tests/systests/test_jenkins_artifacts.py

**Comment by grayaii** [comment]
That works. Thanks for the link!
