### ISSUE TITLE
How to build job with "predefined parameters" on a job that does not take parameters

### ISSUE THREAD

**Issue by grayaii** [salimfadhley/jenkinsapi#429]
In Jenkins you can "Trigger/Call builds on other projects" and you can pass in "predefined parameters" as key/value pairs on jobs that are not parameterized.

The key/value pairs appear as env vars in the triggered job.

I can't seem to figure out how to use the api to do this.

I tried passing in "files" to the invoke function, like this: https://github.com/salimfadhley/jenkinsapi/issues/245
But no love.

I also tried passing in build_params to the invoke function but I get:
jenkinsapi.custom_exceptions.BadParams: This job does not support parameters

Looking at the parameters to the invoke function, it doesn't seem like this is supported:
>>> inspect.getargspec(j.invoke)
ArgSpec(args=['self', 'securitytoken', 'block', 'build_params', 'cause', 'files', 'delay'], varargs=None, keywords=None, defaults=(None, False, None, None, None, 5))

Any idea how this can be done?

**Comment by grayaii** [comment]
Here is a screenshot of what I mean.  The _foo job is NOT a parameterized build, but I can trigger _foo and pass in parameters:

<img width="1085" alt="trigger_jobs" src="https://cloud.githubusercontent.com/assets/847072/14179089/a6060396-f72b-11e5-9c1e-24064e8e837f.png">

**Comment by salimfadhley** [comment]
Hey, I dont have a whole load of time for this project any more - but I vaguely remember that we have unit-tests for triggering parametrized builds. If you make a pull request that illustrates a failing test then we can have a go at fixing the library to accommodate your need.

**Comment by lechat** [comment]
It is not possible to do that using REST API. Perhaps Parametrized Trigger plugin does some magic, but we can't do the same.
