### ISSUE TITLE
Is there a way to get a slave node from Jenkins by name and extract its IP?

### ISSUE THREAD

**Issue by omerxx** [salimfadhley/jenkinsapi#440]
I was trying to get a node attributes / config but couldn't manage it.
I want to grab a node by its name an extract some of its attributes ( especially the IP )

Thanks!

**Comment by lechat** [comment]
Node doesn't expose it's config via REST API. Take a look: http://localhost:8080/computer/<node_name>/api/json?pretty=true&depth=3

Best way to approach this problem is to raise issue with plugin developers.
