### ISSUE TITLE
Can the project in PyPi get updated with the new code and methods?

### ISSUE THREAD

**Issue by omerxx** [salimfadhley/jenkinsapi#442]
There are plenty of new additions such as https://github.com/salimfadhley/jenkinsapi/commit/0148c737a5bfe27f9a17e9fceace54b319c87853 that we would be happy to have :)

**Comment by lechat** [comment]
@salimfadhley Could you make a new release?

**Comment by salimfadhley** [comment]
Yes, sure - are you ready?

**Comment by lechat** [comment]
I am ready when I don't see any tests errors in master :+1:

**Comment by omerxx** [comment]
@lechat, @salimfadhley - Thank you guys!

**Comment by salimfadhley** [comment]
Done
