### ISSUE TITLE
[Question] : SSL Error while accessing Jenkins (org specific) using Python 2.7.10 + jenkinsapi

### ISSUE THREAD

**Issue by mramanathan** [salimfadhley/jenkinsapi#452]
Hi All,

Pls excuse me if this forum is not meant to report issues and seek help.

Am using Python v2.7.10 (win os) + jenkinsapi to access my group's (behind firewall) Jenkins. This was attempted while am connected to the office network, not from any public network.

I tried the example code for getting server instance by supplying the URL to jenkins, username and password (also tried with API token) but this is the final error msg after it completes running through various modules.

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Could anyone pls tell me what's missing here ?

Should I move to Python 3 + dependent pkgs ? or can I stay with Python 2.7 but install new pkgs to overcome this problem ?

TIA,
/Ram

**Comment by lechat** [comment]
This has nothing to do with `jenkinsapi`. The error comes from https connection layer, which is handled by `requests` library.
