### ISSUE TITLE
Support Python3.5

### ISSUE THREAD

**Issue by WYSIATI** [salimfadhley/jenkinsapi#457]
Does jenkinsapi support 3.5 now? The doc only mentioned 3.3 and 3.4.

**Comment by lechat** [comment]
So many 3.x versions to test against. Is there a major difference between 3.4 and 3.5?

It shall work fine, while never actually tested with it. Perhaps I will drop tests with 3.3 and add tests with 3.5...

**Comment by WYSIATI** [comment]
@lechat Thanks for replying! I am using this api on 3.5 right now and it works seamlessly so far :-)
